import jsPDF from 'jspdf';
import { ApplicationFormData } from '../types/application';

export async function generateApplicationPDF(formData: ApplicationFormData): Promise<Blob> {
  const doc = new jsPDF();
  let y = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;

  // Header with branding
  doc.setFontSize(24);
  doc.setTextColor(37, 99, 235); // blue-600
  doc.text('Sika Internship Application', pageWidth / 2, y, { align: 'center' });
  y += 12;

  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text('Tera-Tech Ltd • Internship Portal', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // Application Info
  doc.setFontSize(10);
  const appId = formData.applicationId || `sika_${Date.now()}`;
  doc.text(`Application ID: ${appId}`, margin, y);
  doc.text(`Submitted: ${new Date().toLocaleDateString('en-GB')} at ${new Date().toLocaleTimeString()}`, margin + 90, y);
  y += 20;

  // Horizontal line
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 15;

  // 1. Personal Information
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text('1. Personal Information', margin, y);
  y += 10;

  doc.setFontSize(11);
  const about = formData.about || {};
  doc.text(`Full Name: ${about.firstName || ''} ${about.lastName || ''}`, margin, y); y += 8;
  doc.text(`Nationality: ${about.nationality || '—'}`, margin, y); y += 8;
  doc.text(`WhatsApp: ${about.phone || '—'}`, margin, y); y += 8;
  doc.text(`Date of Birth: ${about.dateOfBirth || '—'}`, margin, y); y += 8;
  doc.text(`Language: ${about.language || '—'}     Gender: ${about.gender || '—'}`, margin, y);
  y += 18;

  // 2. Education
  doc.setFontSize(14);
  doc.text('2. Education Background', margin, y);
  y += 10;
  doc.setFontSize(11);
  const edu = formData.education || {};
  doc.text(`School / University: ${edu.schoolName || '—'}`, margin, y); y += 8;
  doc.text(`Location: ${edu.schoolLocation || '—'}`, margin, y); y += 8;
  doc.text(`Field of Study: ${edu.fieldOfStudy || '—'}`, margin, y); y += 8;
  doc.text(`Level: ${edu.level || '—'}     Program: ${edu.program || '—'}`, margin, y);
  if (edu.previousInternship) {
    y += 8;
    doc.text(`Previous Internship: ${edu.previousInternship}`, margin, y);
  }
  y += 18;

  // 3. Internship Preferences
  doc.setFontSize(14);
  doc.text('3. Internship Preferences', margin, y);
  y += 10;
  doc.setFontSize(11);
  const intern = formData.internship || {};
  doc.text(`Specialty: ${intern.specialty || '—'}`, margin, y); y += 8;
  doc.text(`Experience Level: ${intern.experienceLevel || '—'}`, margin, y); y += 8;
  doc.text(`Preferred Duration: ${intern.duration || '—'}`, margin, y); y += 8;
  doc.text(`Availability: ${intern.availability || '—'}`, margin, y); y += 12;

  doc.text('Relevant Experience:', margin, y);
  y += 8;
  const experienceText = intern.workExperience 
    ? doc.splitTextToSize(intern.workExperience, pageWidth - margin * 2)
    : ['No experience provided'];
  doc.text(experienceText, margin, y);
  y += experienceText.length * 7 + 10;

  // 4. Documents & Links
  doc.setFontSize(14);
  doc.text('4. Documents & Online Profiles', margin, y);
  y += 12;

  doc.setFontSize(11);
  const uploads = formData.uploads || {};

  // Documents
  doc.text('Documents:', margin, y); y += 8;
  if (uploads.cvUrl) { doc.text(`• CV: ${uploads.cvUrl}`, margin + 5, y); y += 7; }
  if (uploads.applicationLetterUrl) { doc.text(`• Application Letter: ${uploads.applicationLetterUrl}`, margin + 5, y); y += 7; }
  if (uploads.passportPhotoUrl) { doc.text(`• Passport Photo: ${uploads.passportPhotoUrl}`, margin + 5, y); y += 7; }
  if (uploads.supportLetterUrl) { doc.text(`• Support Letter: ${uploads.supportLetterUrl}`, margin + 5, y); y += 7; }

  // Social Links
  if (uploads.socialLinks && (uploads.socialLinks.linkedin || uploads.socialLinks.github || uploads.socialLinks.portfolio)) {
    y += 8;
    doc.text('Social Links:', margin, y); y += 8;
    if (uploads.socialLinks.linkedin) { doc.text(`• LinkedIn: ${uploads.socialLinks.linkedin}`, margin + 5, y); y += 7; }
    if (uploads.socialLinks.github) { doc.text(`• GitHub: ${uploads.socialLinks.github}`, margin + 5, y); y += 7; }
    if (uploads.socialLinks.portfolio) { doc.text(`• Portfolio: ${uploads.socialLinks.portfolio}`, margin + 5, y); y += 7; }
  }

  // Final line + footer
  y = 275;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text('This document was automatically generated by the Sika Internship Portal.', pageWidth / 2, y, { align: 'center' });
  doc.text('Tera-Tech Ltd • Bamenda, Cameroon', pageWidth / 2, y + 6, { align: 'center' });

  return doc.output('blob');
}